name: Check - Lint and Test

on:
  pull_request:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - name: Set up Go
        uses: actions/setup-go@7b8cf10d4e4a01d4992d18a89f4d7dc5a3e6d6f4 # v4
        with:
          go-version: '1.24'
      - name: Install Task
        run: |
          echo "Installing Task..."
          sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d
      - name: Install golangci-lint
        run: |
          echo "Installing golangci-lint..."
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b ./bin v2.0.2
      - name: Run Lint
        run: |
          echo "Running lint..."
          ./bin/task lint
      - name: Run Tests
        run: |
          echo "Running tests..."
          ./bin/task test
