name: Check - Lint and Test

on:
  push:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'
      - name: Install Task
        run: |
          echo "Installing Task..."
          sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d
      - name: Install golangci-lint
        run: |
          echo "Installing golangci-lint..."
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b ./bin v2.0.2
      - name: Run Lint
        run: |
          echo "Running lint..."
          ./bin/task lint
      - name: Run Tests
        run: |
          echo "Running tests..."
          ./bin/task test
