name: Lint Code - Viron/linter

on:
  push:
    branches:
      - develop
    paths:
      - "**.go"
      - "Taskfile.yml"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'
      - name: Install Task
        run: |
          echo "Installing Task..."
          sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d
      - name: Run Lint
        run: |
          echo "Running lint..."
          ./bin/task lint
